version: '3'
services:
  gns3:
    build: .
    privileged: true
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - gns3Docker:/var/lib/docker
      - /persist/gns3/root/:/root/
volumes:
  gns3Docker:
